version: '3'

services:
  ai-service:
    container_name: kau-medicare-ai
    image: python:3.9-slim
    volumes:
      - /home/ubuntu/deploy/python-service:/app
    working_dir: /app
    ports:
      - "5000:5000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    command: >
      bash -c "apt-get update && 
              apt-get install -y curl libglib2.0-0 libsm6 libxext6 libxrender-dev libgl1-mesa-glx cmake build-essential &&
              pip install dlib==19.24.0 &&
              pip install -r requirements.txt &&
              python app.py"

    healthcheck:
      test: curl -f http://localhost:5000/ || exit 1
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    networks:
      - app-network

  app:
    container_name: kau-medicare-app
    image: openjdk:17
    volumes:
      - ./web:/root
      - ./wallet:/opt/wallet
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=${DB_URL}
      - SPRING_DATASOURCE_USERNAME=${DB_USER_NAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - AI_SERVICE_URL=http://ai-service:5000
    command: java -jar /root/app.jar
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge